### ISSUE TITLE
Set inputs on DSK function as Set inputs on USK

### ISSUE THREAD

**Issue by ArielBonardi** [bitfocus/companion-module-bmd-atem#85] opened 2020-09-27 21:25 UTC
Hi, the PRESETS FOR DSK 1 are working as PRESETS FOR M/E 1 KEY 1.
I try to change this, adding a new action as "atem mini pro: Set inputs on Downstream KEY" but the error persist.

Any idea how to fix it?

Thanks, 
Ariel

win 10 2004
Bitfocus Companion 2.1.0 (47823d0-2493)
Atem mini pro
ATEM 8.5

**Comment by Julusian** [comment] 2020-09-28 08:42
Duplicate of #79 #70

This is fixed in the 2.1.1 beta builds

**Closed by Julusian** 2020-09-28 08:42 UTC

**Comment by ArielBonardi** [comment] 2020-09-28 14:21
Sorry, thanks for reply.
