### ISSUE TITLE
Television studio pro 4k error as instance

### ISSUE THREAD

**Issue by haeleng** [bitfocus/companion-module-bmd-atem#115] opened 2021-01-24 15:48 UTC
[BUG] When I try to make instance in companion for the model TVS pro 4k it gives on error Houston we have a problem.
Selecting a different model works fine.

**Comment by Julusian** [comment] 2021-01-24 17:12
Duplicate of #102, #113

Fixed as of companion-2.2.0-c81e24b-2796

**Closed by Julusian** 2021-01-24 17:12 UTC
