### ISSUE TITLE
ATEM Constellation 8K SuperSource 2 missing

### ISSUE THREAD

**Issue by worktank** [bitfocus/companion-module-bmd-atem#103] opened 2021-01-08 23:12 UTC
When assigning program or preview buttons of any ME shows  two instances of SS1 (SuperSource 1),and no instances of SS2 (SuperSource 2).   Both SS1 buttons properly control SS1. 

Would love to be able to add SS2 directly and not have to control with a macro.

I have an ATEM Constellation 8K running software 8.1.2 and am controlling with Companion 2.1.2.  Changing the instance type between Auto Detect, Constellation 8k Mode, or Constellation 4k Mode all behave the same.  

Thanks for the great software.

**Comment by Julusian** [comment] 2021-01-08 23:13
Duplicate of https://github.com/bitfocus/companion-module-bmd-atem/issues/88

This is fixed in the 2.2.0-77ba794-2756 beta build and newer

**Closed by Julusian** 2021-01-08 23:13 UTC
Labels: bug
