### ISSUE TITLE
Add command to set ATEM input label

### ISSUE THREAD

**Issue by aaronpk** [bitfocus/companion-module-bmd-atem#154] opened 2021-09-21 17:38 UTC
The node ATEM library already supports setting input labels, so it'd be great to get support for this in Companion!

* https://github.com/nrkno/tv-automation-atem-connection/blob/16c3cdd6b7fedb4770a2841ff193b1930de7eeb5/src/atem.ts#L518
* https://github.com/nrkno/tv-automation-atem-connection/blob/16c3cdd6b7fedb4770a2841ff193b1930de7eeb5/src/commands/Inputs/InputPropertiesCommand.ts#L7

My use case is using an SDI router to change which of the 20 sources are plugged in are routed to which of the 8 inputs on the ATEM Mini Extreme, so I want the labels on the ATEM to update when I change sources on the SDI router to match.

**Comment by Julusian** [comment] 2021-09-25 19:31
Duplicate of #43.
The library supports setting the text labels, but not the labels shown on the multiviewer. So this feature isn't really doable right now. I have been wanting to, but it's going to be quite a lot of time and effort to get the image updating wolfing, especially as different models need it done slightly differently

**Closed** 2021-09-25 19:31 UTC
