### ISSUE TITLE
Mix and Cut operation

### ISSUE THREAD

**Issue by Bstanhope** [bitfocus/companion-module-bmd-atem#75] opened 2020-09-04 12:57 UTC
I have two streamdecks with the same issue: The mix and cut operation on the streamdeck itself doesn't work. In the webinterface emulator the buttons work perfectly. I use the Atem Studio HD
When I press the Cut button (atem: CUT Operation) the screen switches fast to the selected input and back. 
When I press the Mix button (atem: AUTO transition operation) , the mix transition moves 10% and stops. When I press the mix button again, it process an other 10%. 
I found a solution for the Mix by using a macro with only the Mix transition in it. I think it's not the way it should work.

**Comment by Julusian** [comment] 2020-09-04 14:23
Are you running a build between companion-2.1.1-5c01252-2529 and companion-2.1.1-e442c8c-2555?
This sounds like a confirmed (and now fixed) bug in companion between those versions.

Either way, this is not a bug in this module as it works in the web emulator.

**Closed by Julusian** 2020-09-04 14:23 UTC
