### ISSUE TITLE
[BUG] Message error while connecting ATEM Television Studio Pro 4K

### ISSUE THREAD

**Issue by Jeannickeldebb** [bitfocus/companion-module-bmd-atem#102] opened 2020-12-30 17:56 UTC
Hi,

I try to control my ATEM Television Studio Pro 4K with my Stream Deck XL by assigning buttons presets through Companion and I get this error message :

"instance(atem): Connected to a ATEM Television Studio Pro 4K, but instance is configured for TV Studio Pro 4K. Change instance to 'Auto Detect' or the appropriate model to ensure stability."

I either tried "Auto detect" and "TV Studio Pro 4K" in model section of module settings but always the error is listed.
It seems that the ATEM send "ATEM Television Studio Pro 4K" as model option and Companion is waiting for "TV Studio Pro 4K" and the result is that I can't affect buttons because it produce an error.

My stream Deck work perfectly with my HyperDeck Studio Mini and with my other ATEM Mini Pro ISO. I only have this error with the ATEM Television Studio Pro 4K.

I use the Mac Companion v2.2.1 (2.1.2-f4bcaf3-2679) on OS X Catalina.

Someone has an idea to fix this issue?
Thanks a lot

<img width="1680" alt="Capture d’écran 2020-12-30 à 18 55 19" src="https://user-images.githubusercontent.com/76063123/103371797-a5306f80-4ad0-11eb-9927-e855ad97d613.png">

<img width="1676" alt="Capture d’écran 2020-12-30 à 19 22 25" src="https://user-images.githubusercontent.com/76063123/103373165-7d430b00-4ad4-11eb-806c-70fda6294544.png">

**Comment by ely105** [comment] 2020-12-31 00:35
I just noticed the same issue on our TV Studio 4k.  Also I am seeing some weirdness that if you change from auto-detect and then apply it crashes companion.  When you start it back up it still shows the ATEM instance and talks to the unit ok but then when you try to edit or create a new button atem isn't on the list at all.  You have to delete the atem instance and re-add to get it back.  I've been using this with a Constellation, hyperdecks, Videohub for months and it's never had any issues quite like this.  I was assuming that it's just trying to match the text string coming back from the atem and not matching but it seems a bit more unstable.  -m

**Comment by Jeannickeldebb** [comment] 2020-12-31 12:15
@Julusian of course I applied changes and cleared my log but it happen again every time I choose TV Studio Pro 4K.

Anyway, I choose TV Studio Pro HD in the menu and it work perfectly.

Maybe the interface have been badly coded for this menu because in the companion choose model menu you have :
1 - TV Studio
2 - TV Studio HD
3 - TV Studio Pro 4K
4 - TV Studio Pro HD

while in the Blackmagic hierarchy TV Studio Pro 4K is the best model and so should be in 4th position.

@ely105 I have the same crashing issues with companion when I choose Auto detect.

**Comment by Julusian** [comment] 2020-12-31 15:20
@ely105 Im not able to reproduce that crashing in 2.1.2, Ill give it another try later to confirm. Did the crashing happen in 2.1.0? Perhaps you could give a beta build of 2.2.0 a quick try too (backup your config first, it might mess thingsup), as that should behave better

@Jeannickeldebb I dont understand how that could happen with the correct model selected. 
The module matches the device based on a numeric id the atem sends. Intenrlly this module has a feature list defined for each model.
The logging of that error is defined as 'if config is not autodetect, and config does not match what we are connected to, then log error`. But the autodetect value was changed accidently in one place, so would always be seen as not matching in that check. So with the correct model selected in the config I do not see how it could be logged.

The order of the models is a choice, they are sorted by name. The internal ids are in the order you expect. But perhaps the models should be sorted newest to oldest instead of name?

Would you mind running this tool and sending me the result https://builds.julusian.dev/atem/ ? It is possible the ids for the tvs pro 4k and tvs pro hd are inverted, as I have never had either of them to test with

**Comment by Jeannickeldebb** [comment] 2020-12-31 16:29
@Julusian Here is the data result file of your tool. (I change the extension in .log to share the file .data was not authorized.
I also have crash on version 2.1.2 when I select Pro Studio 4K (see screenshot)
Thx

![Capture d’écran 2020-12-31 à 17 10 23](https://user-images.githubusercontent.com/76063123/103417814-8099cd80-4b8c-11eb-94b5-f9f7f5ddaeaa.png)


[TVStudPro4K-Jeannickeldebb.log](https://github.com/bitfocus/companion-module-bmd-atem/files/5757729/TVStudPro4K-Jeannickeldebb.log)

**Comment by Julusian** [comment] 2021-01-03 22:02
OK, I have gotten to the bottom of this issue. It was caused by the feature list for the model stating it used fairlight, but then not having any inputs and some other bits of the module assumed there would be at least one.

I have a fix that will go into a 2.2 build soon, but for now you are probably best to stick with forcing it to be treated as a tvs hd pro. But in doing so, you will loose the actions to control clips with the media players

**Comment by Jeannickeldebb** [comment] 2021-01-05 09:41
Hi,
Ok great, look forward to installing the new update!
I think it will be fine with tvs HD until update comes, the StreamDeck should do the job as we have an HyperDeck for clips and this part works perfectly.
Thank you for your involvement on resolving this issue.
Best

**Comment by AlexLueck67** [comment] 2021-01-08 19:07
we have the same problem, and are also looking for a solution here.
When the update is ready I would be happy if I could get some info.

**Comment by ely105** [comment] 2021-01-13 01:22
Sorry we were on other things. We tried 2.2.2-…2794 and while no crashes it just says “connecting” but never succeeds. ATEM software control is fine from same PC.

**Comment by Julusian** [comment] 2021-01-17 14:10
@ely105 that should be fixed with companion-2.2.0-c81e24b-2796

The original bug reported here is also fixed

**Closed** 2021-03-13 23:15 UTC
Labels: bug
