### ISSUE TITLE
Feature Request: Add "SELECTABLE ROUTING" actions to ATEM Module (AUX, PGM, PVW, 2ME, Multiview etc...)

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-bmd-atem#215] opened 2022-11-11 22:01 UTC
_PREFACE: This feature already exists within the [videohub module](https://github.com/bitfocus/companion-module-bmd-videohub). Hopefully this would be easy to port over from videohub, because it would be very valuable to add similar function within the ATEM module._

### Selectable Routing 

The two actions that currently exist in videohub are: 

```
videohub: Select Destination
videohub: Route source to selected destination
```

### Need & Usecase 

While the ATEM module currently supports routing single AUX channels with the `atem: Aux/Output: Set source` action, it only routes 1 source to 1 destination, requiring a massive matrix to build out the associated buttons. This would be unwieldily to say the least, but with Companion's 99 page limit, this also becomes impossible. 

These new actions should be able to route whatever number of inputs ATEM supports...ie In1-40, 1ME's PGM/PVW, 2/3/4ME etc, Supersource, Clean Feed 1 and 2, Black, Color 1 and 2, Color Bars, etc.... to all the outputs the ATEM supports... ie AUX 1/2/3/4...etc, PGM, PVW, 2ME PGM/PVW, 3ME, 4ME etc.

### Variables & Feedback 

Associated variable names and feedback are: 

```
videohub: Change background color by selected destination
videohub: Change background color by route to selected destination
```

It would be great if the associated feedback could include not just the background and foreground color changes, but also all the latest Companion feedback changes including text, text size, text position, png, png position... 

### Additional Destination Options for Customized Switching

In addition to the AUX, PGM/PVW, 2ME etc destinations, it would be helpful to add Supersource Boxes, USKs 1-4, and DSK 1&2 to the Destinations available in the future `atem: Select Destination` action. The benefit is customizable switching could fit into a single Stream Deck page (ie selectable buttons for 1ME, 2ME, AUX1, KEY 1, DSK1 could control a select number of source buttons ie Cam 1,2,3, Hyperdeck, Computer slides, Supersource, MP1, MP2 etc, without having to flip through multiple Companion pages for each output/destination).

### Examples from videohub module

Here's an example of how videohub utilizes the Select Destination action:

<img width="655" alt="Screenshot 2022-11-11 at 1 44 22 PM" src="https://user-images.githubusercontent.com/76959770/201432947-ee44937b-005d-458a-aaef-5577e1bc2c9b.png">

...And here's how videohub module utilizes the Route Source to Selected destination action:

<img width="642" alt="Screenshot 2022-11-11 at 1 45 14 PM" src="https://user-images.githubusercontent.com/76959770/201432948-0151c013-0c33-4777-aa40-aaf4bcabc4fc.png">

### ASSOCIATED FEATURE: ROUTE MULTIVIEWER WINDOWS

In the same manner as routing Program/Preview/2ME/AUX, making the Multiviewer windows routable would make operating this matrix manageable on a Stream Deck.

The two actions & feedback would look like: 
```
atem: Select Multiview Window
atem: Route source to selected Multiview Window
```

```
atem: Change style properties by selected Multiview Window
atem: Change style properties by route to selected Multiview Window
```

Thank you!

**Comment by jalmar2000** [comment] 2022-11-15 19:32
Today we have received the constellation 4M/E and i was struggling with the same problem. Somewhere else I read that you can just use the videohub module with the new Atem constellations. And... it actually worked. I just put in the ip address of the atem in the videohub module and it recognized all the inputs and outputs aswell. I don't know what atem you are using but you should give this a try and please let me know which switcher you are using because we have some other models as well and I am curious if it will work on those as well(Can't do any testing with those right now.)

**Comment by davidjoshuaford** [comment] 2022-11-15 19:41
Hi Jalmar, I'm aware of the videohub module, as mentioned in the preface, and my request here is to bring the selectable routing of the videohub over to the atem module, since it will be more reliable to administer a single module per atem rather than two. Also I have been having problems with the videohub module constantly connecting/disconnecting from the atem. I'm using ATEM 2ME Constellation HD. And the other reason to bring the videohub's selectable routing into the atem module is because the atem module is much more fleshed out, and supports variables such as short name labels, and not just long name labels like the videohub.

**Comment by Julusian** [comment] 2022-11-20 21:58
duplicate of #157

**Closed** 2022-11-21 00:02 UTC

**Comment by davidjoshuaford** [comment] 2022-11-28 16:53
Thanks Julian! I'll test it out this week when I'm back in the studio.
