### ISSUE TITLE
ATEM Mini Pro: missing Multiview option on Aux 1 (HDMI out)

### ISSUE THREAD

**Issue by Pekyyyyy** [bitfocus/companion-module-bmd-atem#65] opened 2020-06-17 09:31 UTC
Set AUX Bus action is missing a dropdown option in Input for a MVW/Multiview. Likely because other ATEMs cannot display Multiviews on Auxes, but ATEM Mini can.

**Comment by Julusian** [comment] 2020-06-17 10:12
Duplicate of #61 
I will get this done soon, hopefully I can tonight

**Closed by Julusian** 2020-06-17 10:12 UTC
