### ISSUE TITLE
 Getting a warning: Connected to a ATEM Mini, but instance is configured for Mini. 

### ISSUE THREAD

**Issue by DanDiamond** [bitfocus/companion-module-bmd-atem#99] opened 2020-12-14 16:45 UTC
I'm seeing this warning in the log:  Connected to a ATEM Mini, but instance is configured for Mini. It suggests that I change to auto detect but still seeing the same warning.

**Comment by Julusian** [comment] 2020-12-28 20:26
Duplicate of #97

**Closed by Julusian** 2020-12-28 20:26 UTC
