### ISSUE TITLE
[BUG] "ATEM: Set inputs on Downstream KEY" not working

### ISSUE THREAD

**Issue by Gromit90** [bitfocus/companion-module-bmd-atem#90] opened 2020-10-29 11:57 UTC
Hi

The "atem: Set inputs on Downstream KEY" not working.
This action changes the Upstream key instead.

When I run the action to set Mediaplayer 1 as the fill- and key-source to the downstreamkey 1 or 2 the upstreamkey fill and key-source changes to Mediaplayer 1 instead of the Downstream key.

**Comment by Julusian** [comment] 2020-10-29 11:58
Duplicate of #79 #70 #85

Use a 2.1.1 beta build, this has been long fixed in those.

**Closed by Julusian** 2020-10-29 11:58 UTC

**Comment by Gromit90** [comment] 2020-10-29 12:10
Where do I find the Beta download?

**Comment by McHauge** [comment] 2020-10-29 12:13
@Gromit90 here is a link: https://bitfocus.io/companion/download/builds/
![image](https://user-images.githubusercontent.com/31018035/97572412-79b5d980-19e8-11eb-9121-821dde3f966b.png)
