### ISSUE TITLE
Supersource 2 incorrectly listed and mapped to Supersource 1 (Constellation)

### ISSUE THREAD

**Issue by singletrackrecs** [bitfocus/companion-module-bmd-atem#107] opened 2021-01-12 17:37 UTC
In the preview select commands, Supersource 1 appears twice instead of Supersource 2 being available, this also applies to the feedback module. Not sure if it applies to other lists like the program selection etc.

![bug](https://user-images.githubusercontent.com/75907707/104342641-f558fa00-54f2-11eb-86b1-3e711464c405.png)

**Comment by Julusian** [comment] 2021-01-12 17:59
Duplicate of https://github.com/bitfocus/companion-module-bmd-atem/issues/103, #88

This is fixed in the 2.2.0-77ba794-2756 beta build and newer

**Closed by Julusian** 2021-01-12 17:59 UTC

**Comment by singletrackrecs** [comment] 2021-01-17 18:45
Thank you that's great that you've fixed it. Are you able to let me know (or point me to any isntructions) of how to update to the latest version of the instance in Companion please? i can't figure out how you see which version of a module you are using (or update it) in the Companion GUI. Thanks again
