### ISSUE TITLE
Implement two step routing like on BM Videohub

### ISSUE THREAD

**Issue by cyblex1** [bitfocus/companion-module-bmd-atem#157] opened 2021-10-10 19:35 UTC
It would be nice to be able to do the routing of Aux/Out like on the Videohub:
First select Output next select the source.
Otherwise you need a lot of pages to assign all the outputs.
I tried to do this the other way: First  setting a custom variable with the source afterwards i tried to assign a output button, but i was not able to use a custom variable as the source.

As we use a constellation there are 24 Outs with possible 40+internal sources (MEs, etc)
Also the same is for all the mutliview positions. As there are 16 positions times 4 mutliviews that is a lot of buttons for full flexibility.

**Comment by BoguschMedia** [comment] 2022-10-10 12:21
i don't have a constellation model but in some forums there were infos about the option to use the videohub protocol to switch the outputs. so this would be a good workarround. 
but longterm there is a need for having a solution of saving buttons with a variable-based switch. as more and more models coming out having more and more outputs.

**Comment by jalmar2000** [comment] 2022-10-23 17:48
If you could also be able to add the same variable to the feedback part of an aux source selection then we would also be able to see the current source showing on the selected output.

**Comment by jalmar2000** [comment] 2022-11-15 19:36
> i don't have a constellation model but in some forums there were infos about the option to use the videohub protocol to switch the outputs. so this would be a good workarround. but longterm there is a need for having a solution of saving buttons with a variable-based switch. as more and more models coming out having more and more outputs.

We have received our 4M/E constellation today and I can confirm that this indeed works and even recognizes the inputs and outputs aswell.

**Comment by Julusian** [comment] 2022-11-21 00:26
cc @davidjoshuaford

I am wondering if it would be sufficient to do #187 (for to the outputs) instead?
With custom variables, It doesn't sound necessary for this module to implement the full two step flow itself.

Instead you can, set a 'destination' custom-variable with one set of buttons. And then other buttons can use that variable as the destination in their routing. Or they can set a second 'source' custom-variable so that you can have a dedicated take button.
And you can use the builtin 'compare variable' feedbacks to indicate what is currently selected.

This doesnt even sound like it is going to be any more work to use

One quirk that bugs me about the implementation in the videohub module is that upon reconnection, it sets the current destination to 1. I kept routing to that accidentally enough, that I created a 'fix output 1' button on my routing page. But with the custom-variables, you have the ability to define the startup destination.

**Comment by cyblex1** [comment] 2022-11-21 08:54
Hi,

Your workaround is also good, and this was also my first solution attempt:

You can set a destination Variable, but i do not know a way to use a variable as the destination in a button nor do we know how to set a take button with the two variables.

Kind regards

Stefan

**Comment by Julusian** [comment] 2022-11-21 10:35
@cyblex1 try in the latest beta. I did some updates last night which include #187, so it should be possible to do this manual flow now

**Comment by davidjoshuaford** [comment] 2022-11-30 00:26
Hi @Julusian , the custom variable routing is working well, thanks. 

Two things I've found: 

Feedback states need to accept custom variables for AUX status, and ME for PGM/ PVW: I believe what I'm looking for was in Videohub... the active destination that was selected would be conditional to showing the feedback state for an Input.

ie... I have an array of input buttons 1-20 for example. If I select AUX1, I want the aux feedback on each button to only be highlighted if the input is in AUX 1. So that when I then select AUX 3 for example, I'm only seeing feedback on the buttons as it relates to AUX 1. 

<img width="1310" alt="Screenshot 2022-11-29 at 7 08 12 PM" src="https://user-images.githubusercontent.com/76959770/204677208-06cea043-76ed-4abf-9641-f00879501abe.png">

Let me know if I missed how this could be achieved through the 'compare variable' feedbacks.


Secondly, is it possible to write an expression in the "Input ID" field? 

For example, In the screenshot below, I'm trying to multiply the Input ID "1" by a custom variable called "opA" (for Operator A, to be able to separate out ME2 or AUX switching to an Operator B if necessary). opA would be selectable to 1 or to 0 on a different button, effectively to create an On or Off state.... multiplying the ID number by 1 keeps the number the same (on), and multiplying the number by 0 makes it 0...voiding the ID field for an "off" state. 


<img width="1320" alt="Screenshot 2022-11-29 at 7 15 49 PM" src="https://user-images.githubusercontent.com/76959770/204677186-b68baa85-0c57-4848-a38a-88ea971ba32e.png">

**Comment by amcchord** [comment] 2022-11-30 03:45
FYI you can use the videohub module with an atem constellation and it just works. It’s an undocumented feature.

**Comment by davidjoshuaford** [comment] 2022-11-30 03:48
> 

Hey @amcchord , I have tried that, but I do find the videohub module to be constantly connecting/disconnecting...plus from an administration perspective I find it more reliable to only have 1 module per atem, rather than 2 :)

**Comment by davidjoshuaford** [comment] 2023-01-31 17:08
@Julusian would it be possible to implement the two step variable routing beyond the PGM/ PVW/ AUX, to also include  MP1/ MP2, DSK 1&2, SS Boxes 1-4, USKs 1-4? This would greatly help simplify page builds and usability.

**Comment by Julusian** [comment] 2023-02-01 00:07
It is now possible to use variables in some feedbacks, so hopefully this is possible.
It doesnt allow for parsing expressions like the `1*$(...)` you are trying in that screenshot, hopefully that isnt necessary?

**Comment by davidjoshuaford** [comment] 2023-02-01 01:48
It doesn't work for "internal: Variable: Check value" nor "internal: Variable: Compare two variables". This is because it's just comparing 2 values, rather than 3. 

Is there a way you can think of to isolate the different AUX feedback?

**Comment by davidjoshuaford** [comment] 2023-02-01 16:30
Apart from isolating aux/pvw/pgm feedback, I see in the ATEM variables there are input IDs for SS, USK, DSK as well, but no associated actions, like there are for: 

> atem: ME: Set Program input from variables
> atem: ME: Set Preview input from variables
> atem: Aux/Output: Set source from variables

Could we please get the same "Set SS/USK/DSK input from variables" actions?

**Comment by Julusian** [comment] 2023-02-03 21:26
There should now be the following actions available (depending on hardware support)

![Screenshot from 2023-02-03 21-16-22](https://user-images.githubusercontent.com/1327476/216713708-265f0b35-716b-4fa8-acea-781df157c200.png)

**Comment by davidjoshuaford** [comment] 2023-02-04 20:53
Amazing! I'll check it out, thanks. 

Variables for Media Players and Media Pool Stills would be wonderful (if you have the bandwidth!)

**Comment by davidjoshuaford** [comment] 2023-04-05 00:54
Hi Julian,

I've had more time to play with these variables and am getting stuck on the feedback for 

```
atem: ME: One ME preview source from variables
atem: ME: One ME program source from variables

```

The Program and Preview feedback variables don't seem to be updating correctly. 

<img width="636" alt="Screenshot 2023-04-04 at 8 51 55 PM" src="https://user-images.githubusercontent.com/76959770/229953984-2072b848-7ba3-47a9-9163-2658054bcc2e.png">


The short name codes will reflect the correct input, but the feedback for Program or Preview don't update.

By contrast, the AUX variables do. 

For example, here PVW, PGM, and AUX are stacked on the same button. Each of these variables are assigned the values: 

0 = off
1 = ME1
2 = ME2
3 = ME3 etc

<img width="1183" alt="Screenshot 2023-04-04 at 8 34 08 PM" src="https://user-images.githubusercontent.com/76959770/229953056-dd51653d-77d1-497e-b9d9-4fff07aeb852.png">

For example, to select PVW and switch off the PGM and AUX states, the raw custom variables are updated on a different button:

```
$(internal:custom_pvw) = 1
$(internal:custom_pgm) = 0
$(internal:custom_aux) = 0
```

<img width="230" alt="Screenshot 2023-04-04 at 8 45 25 PM" src="https://user-images.githubusercontent.com/76959770/229953221-a5fbee69-d74a-4443-8c49-64f2f0591fab.png">

In this example, even though Input 2 (CamB) has been selected for Preview and is showing in the shortname (left yellow highlight), it is not highlighting the Preview variable for Input 2 (right yellow highlight). 

<img width="428" alt="Screenshot 2023-04-04 at 8 48 12 PM" src="https://user-images.githubusercontent.com/76959770/229953767-002d7fe6-2dc1-40f6-8abd-53e83db3494e.png">


Any thoughts? 

David

**Comment by davidjoshuaford** [comment] 2023-04-12 14:15
Hi Julian, 

To the best that I've been able to trouble shoot, it appears there's a problem with the variable feedback for Program and Preview: 

```
atem: ME: One ME preview source from variables
atem: ME: One ME program source from variables

```

For example the ME variable field on the Preview feedback does not work with either a numeral (ie ME = 1), or a variable (where the variable =1 for ME1), but it does work when the field is blank. 

<img width="526" alt="Screenshot 2023-04-12 at 10 11 25 AM" src="https://user-images.githubusercontent.com/76959770/231484899-ba64ba66-a691-4cb9-b988-eb69d7c2e5a6.png">

Here's an example where:

```
$(internal:custom_pvw) = 0
$(internal:custom_pgm) = 0
$(internal:custom_aux) = 1
```

Yet, in the screen shot below, you can see that Program and Preview feedbacks are still active, despite their variables being set to "0", which should nullify them, so that only AUX feedback is seen while AUX = 1.

<img width="1710" alt="Screenshot 2023-04-12 at 9 52 56 AM" src="https://user-images.githubusercontent.com/76959770/231485648-df48ee31-90d5-47be-be81-d451d251b1cd.png">

**Comment by Julusian** [comment] 2023-04-12 21:43
Yep, I forgot to account for the zero indexing in those feedbacks... 
I have pushed a fix which will bubble through to the builds in a few hours

**Comment by davidjoshuaford** [comment] 2023-04-12 21:52
Wonderful, thanks! It was perplexing me..!

**Closed** 2023-09-13 20:45 UTC
Labels: enhancement, supported-by-lib
