### ISSUE TITLE
ATEM Television studio pro 4k not recognised in companion as instance

### ISSUE THREAD

**Issue by haeleng** [bitfocus/companion-module-bmd-atem#113] opened 2021-01-24 15:39 UTC
When I make a ATEM instance in companion and select as mocel TV studio pro 4K and press apply changes I get an error Houston we got a problem. When I select a different model like TV studio pro HD for the TV studio pro 4k it works well.

**Comment by Julusian** [comment] 2021-01-24 15:42
Duplicate of #102

Fixed as of companion-2.2.0-c81e24b-2796

**Closed by Julusian** 2021-01-24 15:42 UTC
Labels: bug, duplicate
