### ISSUE TITLE
[BUG] Indexing problem with latest 3.1.0 builds

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion-module-bmd-atem#246] opened 2023-05-09 09:39 UTC
(ATEM Constalletion HD 4 M/E)

Thanks to the use of variables and triggers, i've designed (and currently use) a single page to assign source to my ouputs.
Everything was working fine untill the latest versions of builds past 3.1.0+5771.

To quickly explain how it works : I'm using variables that gets increment or decrement based on two navigationnal buttons (left & right arrows as shown below) 

![p1_s1_310-5771_](https://user-images.githubusercontent.com/80356993/237053800-40969dc5-88b6-4f8f-8d52-d24b22447ccb.png)

A trigger also computes the max and min values in order to get the loop right between the 24 outputs available on this particular ATEM (4 M/E Constellation HD).
So when the variable is superior to 24 it is changed to 1 and when it's inferior to 1 it is changed to 1. 
**So far so good.** 

As shown on the pictures below  the texts displayed under the white arrows are correct.

On output 1 previous page is 24, next page is 2 (as seen on the previous picture).
On output 24 previous page is 23, next page is 1 (as seen below).

![p24_s1_310-5771_](https://user-images.githubusercontent.com/80356993/237053284-54022e7e-a4a6-4187-bbd9-4097dbfb55d2.png)

I'm using the same "trick" to shift my input values in order to get access to the other available inputs, M/Es, CleanFeeds, SuperSources... etc. etc. Of course I'm using a different set of variables, triggers and commands. 

![p1_s4_310-5771_](https://user-images.githubusercontent.com/80356993/237053402-00c84b13-5e0a-4297-bd1c-2130895228d3.png)

**Everything is working fine. Sources are correctly routed**

BUT From 3.1.0+5862 to the current +5866

Indexes get wrong. 

![p1_s1_310-5866_](https://user-images.githubusercontent.com/80356993/237055803-5bebd58f-3147-4937-870d-333a639ffd7d.png)

For some reason the triggers ignore the <1 or >24 conditions.

![p24_s1_310-5866_](https://user-images.githubusercontent.com/80356993/237056045-af123ae3-f752-4a14-a5fb-3403244161b5.png)

Shifts are also impacted with variables being wrongly increased or decreased.

![p1_s4_310-5866_](https://user-images.githubusercontent.com/80356993/237056285-a9bd395d-6fd3-476d-a408-39143ea41879.png)

Variables got 0 and 25 values where the triggers should avoid and reassign them to be 1 and 24.

Is this a bug of some kind in the newer builds or a wrong usage of both variables/triggers I'm using ?

Thanks in advance for any troubleshooting and/or solution to this weird situation.

**Comment by Julusian** [comment] 2023-05-09 10:05
Are you using the `ME: One ME program source from variables` and `ME: One ME preview source from variables` feedbacks here? There was a bug fixed recently where the me input field was off by one compared to every other action and feedback.

I need to re-read this later when I can think better, maybe I will have other ideas then.
Do you know what version you were using which worked?

**Comment by LYMPIA** [comment] 2023-05-09 10:24
Hello Julian, thank you for your response.

Indeed I'm using "Aux/Output: Set source from variables".
But it appears that it's not the problem.
It seems that variables and triggers are not being computed correctly.

I'm just using a set of variables and triggers in order to display and navigate.

**In instance for the right arrow (button 4.31)**:

**Button text string :**
$(internal:custom_OutputNumNextPage)

**Actions**
**internal**: Custom Variable: Set with expression
**Custom variable** : A custom variable (OutputNum)
**Expression**: $(internal:custom_OutputNum)+1

(No other action, step, feedback)

On its change, the custom variable is then monitored by a trigger. Said trigger looks if the variable is >24 or <1 (strictly inferior or superior). But from +5862, it seems the triggers are not correctly computing/monitoring their designated variables.
And It's working fine with +5771.

**Comment by LYMPIA** [comment] 2023-05-09 10:36
> Do you know what version you were using which worked?

As stated above it's working fine with 3.1.0+5771. Beyond this build (from +5862) it is not working correctly.

> Also, I generally wouldn't recommend running the experimental 3.1 builds. They are where we put some upcoming but not very tested changes, and lag behind the beta 3.0 builds on module updates and bug fixes

And you're 100% right. 
We're not using this for critical live shows.
It's done to test new features, experiment new things. 

In this case we could use it in live production. By navigating past the wrong variables and circling around  we're able to get the proper informations displayed. It's just the 0 and 25 that are incorrectly computed by the triggers. As if the operator "strictly" was ignored for some reason.

**Comment by Julusian** [comment] 2023-05-13 10:04
OK, I think this is a core bug rather than this module. 

By doing:
![image](https://github.com/bitfocus/companion-module-bmd-atem/assets/1327476/d23be048-23f6-41a9-b23a-e9ae9dfbbfb5)
![image](https://github.com/bitfocus/companion-module-bmd-atem/assets/1327476/03c4f7c6-fce8-41d4-9d7c-e7133fbf7dab)

The variable will sit at 3 which is out of bounds of the condition. This was caused by https://github.com/bitfocus/companion/commit/671e327fa0b311acf54794f30fead158ca32c8dd, with the debounce causing the event to fire, then some ms the condition would become true. Meaning that when the event fired the condition would always be for the previous run.

**Comment by Julusian** [comment] 2023-05-13 10:33
This should be fixed in the latest beta/develop builds

**Comment by LYMPIA** [comment] 2023-05-15 06:42
Great. Many thanx Juliusan !

**Closed as completed** 2023-06-16 19:00 UTC
