### ISSUE TITLE
[BUG] Instance feedback on Macros - State bugging

### ISSUE THREAD

**Issue by KOHPM** [bitfocus/companion-module-bmd-atem#91] opened 2020-11-02 16:15 UTC
Macros commands are not changing their state correctly, whether recording, waiting, running. The only state that is working is "used".

So upon creating a new macros in Mini Pro and importing the preset, only the "Used" state changes color correctly. all the 3 other one don't function properly .
<img width="906" alt="Screen Shot 2020-11-02 at 11 11 24 AM" src="https://user-images.githubusercontent.com/44657017/97891319-a32e7800-1cfc-11eb-8d82-d5cb08be6b27.png">

**Comment by Julusian** [comment] 2020-12-28 20:53
@KOHPM I am unable to reproduce this issue. Do you have any more information on how to reproduce it?
A lot of macros won't show any other colour as if there are no pauses or user-waits then they will finish executing instantly

**Comment by Julusian** [comment] 2021-01-23 15:58
Closing as I can't reproduce this. If more information can be provided, then this can be reopened

**Closed by Julusian** 2021-01-23 15:58 UTC
Labels: bug
