### ISSUE TITLE
Import does not set the connection inside a Logic condition/feedback

### ISSUE THREAD

**Issue by mrlinden** [bitfocus/companion-module-bmd-atem#328] opened 2024-10-13 08:03 UTC
Example trigger with a condition that contains a Logic expression:
* Event: On condition becoming true
* Condition: internal: Logic: OR
 - ME: One ME preview source: CAM1
 - ME: One ME preview source: CAM2
* Action: ....

If I export and then import the trigger, the connection is not set for the atem within the logical expression, 
which gives for example the following line in user interface;
WnFHDYuNJZhOKjE42Bbcb: preview_bg (undefined)

Other triggers using preview source without a Logic wrapper are imported correctly.

The same happens also when using the same Logic expression in a button feedback.

**Comment by Julusian** [comment] 2024-10-13 13:58
This is not a bug in the module, but in companion.
And it is already fixed in 3.4.2

https://github.com/bitfocus/companion/issues/3053

**Closed by Julusian** 2024-10-13 13:58 UTC
