### ISSUE TITLE
Second Super Source Choice for Program

### ISSUE THREAD

**Issue by CorpRoadie** [bitfocus/companion-module-bmd-atem#155] opened 2021-10-03 20:47 UTC
If you are using a Constellation the choose for the second SuperSource is not there, it is just two #1.  I have tried using the 6000 and changing it to 6001 but that didn't work.  You have two Set Inputs as Super Source 1 and Super Source 1.

**Comment by Julusian** [comment] 2021-10-03 21:16
Duplicate of: #108 #107 #103 #88 

This is fixed in the 2.2 betas, and I think in 2.1.3

**Closed by Julusian** 2021-10-03 21:16 UTC
